-- Employee Table Basic Operations
CREATE TABLE Employee (
    SLNO NUMBER,
    NAME VARCHAR2(30),
    DESIGNATION VARCHAR2(30),
    BRANCH VARCHAR2(30)
);

INSERT INTO Employee VALUES (1,'KRISHNA','ASSISTANT','HYDERABAD');
INSERT INTO Employee VALUES (2,'RAM','MANAGER','CHENNAI');
INSERT INTO Employee VALUES (3,'ASWIN','SUPERVISOR','KERALA');
INSERT INTO Employee VALUES (4,'SUMAYYA','SUPERVISOR','MANGLOORE');

ALTER TABLE Employee ADD Salary NUMBER;
ALTER TABLE Employee RENAME COLUMN NAME TO EMP_NAME;
ALTER TABLE Employee DROP COLUMN Salary;

DELETE FROM Employee WHERE BRANCH='CHENNAI';
SELECT * FROM Employee;