CREATE TABLE Employee(
    EMPNO VARCHAR2(10),
    NAME VARCHAR2(30),
    DESIGNATION VARCHAR2(30),
    BRANCH VARCHAR2(30)
);

INSERT INTO Employee VALUES('E211','SANJAY','MANAGER','CHENNAI');
INSERT INTO Employee VALUES('E364','RAM','SUPERVISOR','CHENNAI');
INSERT INTO Employee VALUES('E453','ASWIN','ASSISTANT','TRICHY');
INSERT INTO Employee VALUES('E896','SUMAYYA','ASSISTANT','MADURAI');
INSERT INTO Employee VALUES('E231','LAKSHMI','MANAGER','MADURAI');

ALTER TABLE Employee ADD Salary NUMBER;
ALTER TABLE Employee MODIFY NAME VARCHAR2(50);

DESC Employee;

DELETE FROM Employee WHERE ROWNUM=2;

TRUNCATE TABLE Employee;
DROP TABLE Employee;