CREATE TABLE Sales(
    SalesId NUMBER,
    Salesmenname VARCHAR2(30),
    Branch VARCHAR2(30),
    Salesamount NUMBER,
    DOB DATE
);

INSERT INTO Sales VALUES(1,'RAM','CHENNAI',5000,TO_DATE('21-12-2009','DD-MM-YYYY'));
INSERT INTO Sales VALUES(2,'ASWIN','KERALA',7000,TO_DATE('10-11-2001','DD-MM-YYYY'));
INSERT INTO Sales VALUES(3,'KRISHNA','KERALA',9000,TO_DATE('15-12-1999','DD-MM-YYYY'));
INSERT INTO Sales VALUES(4,'SUMAYYA','TRICHY',4000,TO_DATE('08-01-2000','DD-MM-YYYY'));
INSERT INTO Sales VALUES(5,'LAKSHMI','CHENNAI',3000,TO_DATE('20-12-1998','DD-MM-YYYY'));

SELECT Branch, SUM(Salesamount) FROM Sales GROUP BY Branch;
SELECT Branch, AVG(Salesamount) FROM Sales GROUP BY Branch;

SELECT Salesmenname, TO_CHAR(DOB,'DD-MON-YY')
FROM Sales
WHERE TO_CHAR(DOB,'MON')='DEC';

SELECT Salesmenname, DOB
FROM Sales
ORDER BY TO_CHAR(DOB,'MONTH');