CREATE TABLE Employee(
    EMPNO VARCHAR2(10),
    NAME VARCHAR2(30),
    DEPT VARCHAR2(30),
    SALARY NUMBER,
    DATEOFJOIN DATE,
    DESIGN VARCHAR2(30),
    BRANCH VARCHAR2(30)
);

SELECT * FROM Employee;
SELECT EMPNO, SALARY FROM Employee;
SELECT AVG(SALARY) FROM Employee;
SELECT COUNT(*) FROM Employee;
SELECT COUNT(DISTINCT NAME) FROM Employee;

SELECT NAME, SUM(SALARY), COUNT(NAME)
FROM Employee
GROUP BY NAME;

SELECT * FROM Employee WHERE SALARY>120000;

SELECT NAME FROM Employee ORDER BY NAME DESC;

SELECT * FROM Employee
WHERE NAME='ASWIN' AND SALARY>50000;